# Generated by Django 3.0.5 on 2020-04-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200412_1620'),
        ('books', '0002_auto_20200411_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paperback',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BookReadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'unread'), ('1', 'reading'), ('2', 'read')], default='0', max_length=56)),
                ('page_reading', models.IntegerField(default=0)),
                ('account', models.ManyToManyField(to='accounts.Account')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
