# Generated by Django 3.0.5 on 2020-04-15 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200415_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookreadstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreadstatus',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreadstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookrequestbuy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrequestbuy',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookrequestbuy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreview',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
