# Generated by Django 3.0.5 on 2020-04-13 13:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookrequestbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequestbuy',
            name='status',
            field=models.CharField(choices=[('0', 'waiting'), ('1', 'approved'), ('2', 'bought'), ('3', 'reject')], default='0', max_length=56),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), size=None), size=None)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
