# Generated by Django 3.0.5 on 2020-04-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookreadstatus',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookrequestbuy',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
