# Generated by Django 3.0.5 on 2020-04-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200416_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
