# Generated by Django 3.0.5 on 2020-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200416_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequestbuy',
            name='book_category',
        ),
        migrations.AddField(
            model_name='bookrequestbuy',
            name='book_category',
            field=models.ManyToManyField(to='books.BookCategory'),
        ),
    ]
