# Generated by Django 3.0.5 on 2020-04-20 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200416_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreadstatus',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
