# Generated by Django 3.0.5 on 2020-04-20 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookreadstatus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadstatus',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
