# Generated by Django 3.0.5 on 2020-04-15 02:57

import components.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('role', models.IntegerField(choices=[(1, 'Sun Admin'), (2, 'Sun Memeber')], default=2)),
                ('is_activate', models.BooleanField(default=False)),
                ('avatar', models.ImageField(null=True, upload_to=components.users.models.user_directory_path)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
