# Generated by Django 3.0.5 on 2020-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('0', 'admin'), ('1', 'normal')], default='1', max_length=128),
        ),
    ]
